# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx1G
loom.platform = neoforge

# Mod properties
mod_version=20.12.0.1
maven_group = com.yesman.epicparcool
archives_name = epicparcool

# Minecraft properties
minecraft_version = 1.21.1

# Dependencies
neoforge_version = 21.1.215


epicfight_version_range=[21.14.4,)
parcool_version_range=[3.4.2.0,)